spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_BEHAVIOUR}

springdoc:
  swagger-ui:
    path: /api/docs

application:
  endpoints:
    api: /api
    mailitem:
      self: /mailitem
      register: /register
      deliver: /deliver
      history: /history
    movement:
      self: /movement
      arrive: /arrive
      depart: /depart