spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_BEHAVIOUR}

application:
  endpoints:
    api: /api
    mail-item:
      self: /mail-item
      register: /register
    movement:
      self: /movement
      arrive: /arrive
      depart: /depart
      deliver: /deliver
      history: /history